using System;

public class Tasks
{
    /*
	 * If we list all the natural numbers below $10$ that are multiples of $3$ or $5$, we get $3, 5, 6$ and $9$. The sum of these multiples is $23$.</p>
Find the sum of all the multiples of $3$ or $5$ below $1000$.
	 */
    public int SumOfMultiplesOf3And5()
	{

		int sum = 0;
		for (int i = 0; i <= 10; i++) {
			if (i%3 = 0 || i%5 = 0 )
			{
				sum += i;
			}
			i++;
		}

        return sum;
	}

    /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
 and, the first terms will be:
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
	find the sum of the even-valued terms.
	 * 	/
	 
	public Class1()
	{
	}
}
