using System;
using static ProjectEulerTasks.Main.Logic.NumberUtilities;

namespace ProjectEulerTasks.Main.Logic
{
    public class EulerTasks
    {
        /*
         * If we list all the natural numbers below $10$ that are multiples of $3$ or $5$, we get $3, 5, 6$ and $9$. The sum of these multiples is $23$.</p>
    Find the sum of all the multiples of $3$ or $5$ below $1000$.
         */
        internal static int SumOfMultiplesOf3And5()
        {
            //initialise the sum of numbers to 0
            int sum = 0;

            //loop thru the numbers 1 to 1000
            for (int i = 0; i < 1000; i++)
            {
                //check if the number is a multiple of 3 or 5 using the remainder operand
                if (i % 3 == 0 || i % 5 == 0)
                {
                    //if it is, add it to the sum
                    sum += i;
                }
            }
            //return the summed value
            return sum;
        }

        /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
         * By starting with 1 and 2, the first 10 terms will be:
         * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
           By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         */

        internal static int SumOfEvenFibonacciNumbers()
        {
            //fibonacci formula: Fn = F(n-1) + F(n-2);
            //int fib1 = 1; 
            int fibValue= 0, next,sum = 0;
           // var fibArray = Array.Empty<int>();
           // fibArray[1] = fib1; fibArray[2] = fib2;
            
            for (next = 1; fibValue <= 4000000; next++)
            {
                 fibValue = GetFibonacciValue(next);
                if (fibValue % 2 == 0)
                {
                    sum += fibValue;
                }
            }

            return sum;
        }

        /*
         * The prime factors of 13195 are 5, 7, 13 and 29
            What is the largest prime factor of the number 600851475143?
        */
        
        internal static long LargestPrimeFactor(long n)
        {
 
            // found a better way, just set the value to max istead of keeping a list
            long primeFactorMax = 2;

            //check if n is less than two, the lowest prime number, if so, return 0 for now
            if (n < 2)
            {
                return 0;
            }
            //if n = 2, the lowest prime number, just return 2
            else if (n == 2)
            {
                return primeFactorMax;
            }
            /*if not,
            check for the possible divisible numbers, if ther are a prime number
            then check if they are a prime factor of n
            add them to the list
            and check for the max value in the list*/
            else
            {
                //for (long i = 2; i < n; i++) -- this takes too long
                for (long i = 0; i < Convert.ToInt64(n/2); i++)
                {
                    if (IsPrimeNumber(i) && (n % i == 0))
                    {
                       primeFactorMax = i;                     
                    }
                }
                return primeFactorMax;
            }
     
        }

        internal static long EfficientLargestPrimeFactor(long number)
        {
            /* - confirm that n is a positive number greater than 1
             * - get the list of prime numbers from 2 to n using Eratosthenes sieve
             * - check if the prime number is a factor of n
             * - get the largest prime factor from the list
             * */

            //set number to the value we are checking for
            //long number = 600851475143;
            if (number <= 1)
            {
                return 0;
            }

            else if (number == 2 || number == 3 || number == 5 || number == 7)
            {
                return number;
            }
            else
            {
                long largestFactor = 1;
                long temp = number;

                // Handle factor 2 separately (optimization for even numbers)
                while (temp % 2 == 0)
                {
                    largestFactor = 2;
                    temp /= 2;
                }
                //next
                // Check odd factors starting from 3
                // Only need to check up to √temp because if temp has a factor > √temp,
                // it can only have one such factor, and that factor would be prime
                for (long i = 3; i * i <= temp; i += 2)
                {
                    while (temp % i == 0)
                    {
                        largestFactor = i;
                        temp /= i;
                    }
                }

                // If temp > 1, then it's a prime factor larger than √original_number
                if (temp > 1)
                {
                    largestFactor = temp;
                }

                return largestFactor;
          
            }
        }

        /*
         * A palindromic number reads the same both ways. 
         * The largest palindrome made from the product of two-digit numbers is 9009 = 91 times 99
         * Find the largest palindrome made from the product of two 3-digit numbers.
        */
        internal static int LargestPalindromeOf3Numbers()
        {
            return 0;
        }

        public EulerTasks()
        {
        }
    }
}