using System;

namespace ProjectEulerTasks.Main.Logic
{
    public class EulerTasks
    {
        /*
         * If we list all the natural numbers below $10$ that are multiples of $3$ or $5$, we get $3, 5, 6$ and $9$. The sum of these multiples is $23$.</p>
    Find the sum of all the multiples of $3$ or $5$ below $1000$.
         */
        internal static int SumOfMultiplesOf3And5()
        {
            //initialise the sum of numbers to 0
            int sum = 0;

            //loop thru the numbers 1 to 1000
            for (int i = 0; i < 1000; i++)
            {
                //check if the number is a multiple of 3 or 5 using the remainder operand
                if (i % 3 == 0 || i % 5 == 0)
                {
                    //if it is, add it to the sum
                    sum += i;
                }
            }
            //return the summed value
            return sum;
        }

        /* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
         * By starting with 1 and 2, the first 10 terms will be:
         * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
           By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         */

        internal static int SumOfEvenFibonacciNumbers()
        {
            //fibonacci formula: Fn = F(n-1) + F(n-2);
            //int fib1 = 1; 
            int fibValue= 0, next,sum = 0;
           // var fibArray = Array.Empty<int>();
           // fibArray[1] = fib1; fibArray[2] = fib2;

            
            for (next = 1; fibValue <= 4000000; next++)
            {
                 fibValue = NumberUtilities.GetFibonacciValue(next);
                if (fibValue % 2 == 0)
                {
                    sum += fibValue;
                }
            }

            return sum;
        }

        
        public EulerTasks()
        {
        }
    }
}